### ISSUE TITLE
TODO until first release

### ISSUE THREAD

**Issue by koppor** [MyLibreLab/MyLibreLab#4]
Lists taks Todo until a first release and a good place for new developers is established

- [ ] reformat all code
- [ ] minor code clean ups
- [ ] check netbeans development for UI
- [ ] clean up repo (delete binary files)
- [ ] extract examples from distribution folder
- [ ] write how to setup IDE
- [ ] installation guide

**Comment by Foadsf** [comment]
## German words:

* abbrechen --> abort

**Comment by koppor** [comment]
We cannot fully convert to IntelliJ. The UI is created using the NetBeans' FORM designer. It is NOT available for free in IntelliJ: https://stackoverflow.com/a/8414933/873282

We do not want to spend 65€/year/developer for having the UI editable in IntelliJ

**Comment by Foadsf** [comment]
@koppor any chance we can make the project IDE independent?

**Comment by koppor** [comment]
@Foadsf Who wants to rewrite the project in his favourite language? Python and QT anyone? 😄
